# =========================================================
# Jalousie Wohnzimmer West – Konfiguration
# =========================================================
# Dieses File definiert:
# - Helper-Entitäten (input_boolean, input_number, etc.)
# - Template-Cover (MQTT → LOGO Steuerung)
# - Blueprint-Verwendung (t0bybr/blinds.yaml)
#
# Tilt-System:
# - tilt_current: Automatisch getrackt (0% = vertikal, 100% = horizontal)
# - tilt_target: Zielwert bei Toggle (Standard: 75%)
# - tilt_enabled: An/Aus Toggle (2× Hoch-Taste)
# - Intelligente Drift-Vermeidung durch Referenz-Methode
#
# State Machine:
# - idle, moving_user, moving_automation, moving_wind
# - moving_tilt, adjusting_tilt_ref, recovering_position
#
# MQTT Topics:
# - logo/register/set/<register>: Zielposition in Ticks
# - logo/coil/set/<coil>: Motor an/aus (ON/OFF)
#
# =========================================================
# FÜR NEUE JALOUSIEN: TODO-LISTE
# =========================================================
# Wenn du eine neue Jalousie einrichtest, musst du folgende Werte anpassen:
#
# 1. MQTT SENSOREN (von deiner LOGO-Konfiguration abhängig):
#    - position_ticks_sensor_entity_id: sensor.mosquitto_broker_mqtt_logo_hr_XXX_position_raw
#    - movement_status_sensor_entity_id: sensor.mosquitto_broker_mqtt_logo_hr_XXX_status
#    - up_button_entity_id: binary_sensor.mosquitto_broker_mqtt_logo_coil_X
#    - down_button_entity_id: binary_sensor.mosquitto_broker_mqtt_logo_coil_Y
#    → Überall in diesem File suchen nach "hr_104" und "coil_9/8/8303/8304"
#
# 2. LOGO REGISTER & COILS:
#    - register_target: XXX (LOGO Register für Zielposition)
#    - register_max_ticks_limit: XXX (LOGO Register für max. Fahrweg)
#    - register_counter: XXX (LOGO Register für Position-Backup)
#    - coil_up: XXXX (LOGO Coil zum Hochfahren)
#    - coil_down: XXXX (LOGO Coil zum Runterfahren)
#
# 3. KALIBRIERUNG (durch Messen ermitteln):
#    - max_travel_ticks: XXX (Gesamter Fahrweg 0% → 100%)
#    - tilt_ticks_close: XX (Ticks von horizontal zu vertikal, typ. 14)
#    - tilt_ticks_open: XX (Ticks von vertikal zu horizontal, typ. 15)
#    - min_motor_ticks: X (Minimale Motorlaufzeit, typ. 5)
#
# 4. TILT-KONFIGURATION:
#    - tilt_target_default: XX (Standard-Neigung beim Toggle, typ. 75%)
#    - tilt_position_threshold_pct: XX (Max. Position für Tilt, typ. 80%)
#
# 5. ENTITY-NAMEN:
#    - Alle "blinds_0_living_room_west" durch deinen Raum-Slug ersetzen
#    - name: "living_room_west" (im Blueprint)
#    - floor: "0" (Stockwerk)
#
# Suche im File nach "TODO:" für alle Stellen die angepasst werden müssen!
# =========================================================

# =========================================================
# Helper-Entitäten
# =========================================================

input_boolean:
  blinds_0_living_room_west_counting:
    name: "Jalousie West - Klick-Zählfenster aktiv"
    icon: mdi:timer-sand
  blinds_0_living_room_west_tilt_enabled:
    name: "Jalousie West - Neigung aktiviert"
    icon: mdi:blinds
  blinds_0_living_room_west_tilt_lock:
    name: "Jalousie West - Tilt Operation Lock (intern)"
    initial: false
    icon: mdi:lock

input_select:
  blinds_0_living_room_west_state:
    name: "Jalousie West - Status"
    options:
      - idle
      - moving_user
      - moving_automation
      - moving_wind
      - moving_tilt
      - adjusting_tilt_ref
      - recovering_position
    initial: idle
    icon: mdi:state-machine

input_text:
  blinds_0_living_room_west_sequence_id:
    name: "Jalousie West - Sequenz-ID (intern)"
    initial: ""
  blinds_0_living_room_west_last_direction_text:
    name: "Jalousie West - Letzte Tastenrichtung"

input_number:
  # System-Parameter
  blinds_0_living_room_west_max_travel_ticks:
    name: "Jalousie West - Max. Fahrweg (Ticks)"
    min: 0
    max: 999
    mode: box
    step: 1
    icon: mdi:map-marker-distance

  blinds_0_living_room_west_position_backup:
    name: "Jalousie West - Position Backup (intern)"
    min: 0
    max: 999
    mode: box
    step: 1
  blinds_0_living_room_west_movement_start_ticks:
    name: "Jalousie West - Last Movement Start (Ticks)"
    min: 0
    max: 999
    mode: box
    step: 1
  # LOGO Register-Nummern
  blinds_0_living_room_west_logo_register_counter:
    name: "Jalousie West - LOGO Register Counter"
    min: 0
    max: 999
    mode: box
    step: 1

  blinds_0_living_room_west_logo_register_target:
    name: "Jalousie West - LOGO Register Target"
    min: 0
    max: 9999
    mode: box
    step: 1

  # LOGO Coil-Nummern
  blinds_0_living_room_west_logo_coil_up:
    name: "Jalousie West - LOGO Coil Hoch"
    min: 0
    max: 9999
    mode: box
    step: 1

  blinds_0_living_room_west_logo_coil_down:
    name: "Jalousie West - LOGO Coil Runter"
    min: 0
    max: 9999
    mode: box
    step: 1

  # Bewegungsstatus
  blinds_0_living_room_west_last_moving_state:
    name: "Jalousie West - Letzter Bewegungsstatus"
    min: 0
    max: 3
    mode: box
    step: 1
    icon: mdi:arrow-up-down

  # Tilt-System
  blinds_0_living_room_west_tilt_current:
    name: "Jalousie West - Aktuelle Neigung"
    min: 0
    max: 100
    step: 1
    mode: slider
    unit_of_measurement: "%"
    icon: mdi:angle-acute

  blinds_0_living_room_west_tilt_target:
    name: "Jalousie West - Ziel-Neigung"
    min: 0
    max: 100
    step: 5
    mode: slider
    unit_of_measurement: "%"
    initial: 75
    icon: mdi:target

  blinds_0_living_room_west_tilt_ticks_close:
    name: "Jalousie West - Ticks für 0% Tilt (runter)"
    min: 0
    max: 50
    step: 1
    mode: box
    initial: 14  # TODO: KALIBRIERUNG - Messen: Ticks von horizontal zu vertikal
    icon: mdi:arrow-collapse-vertical

  blinds_0_living_room_west_tilt_ticks_open:
    name: "Jalousie West - Ticks für 100% Tilt (hoch)"
    min: 0
    max: 50
    step: 1
    mode: box
    initial: 15  # TODO: KALIBRIERUNG - Messen: Ticks von vertikal zu horizontal
    icon: mdi:arrow-expand-vertical

  blinds_0_living_room_west_min_motor_ticks:
    name: "Jalousie West - Minimale Motorlaufzeit (Ticks)"
    min: 1
    max: 10
    step: 1
    mode: box
    initial: 5  # TODO: KALIBRIERUNG - Minimale Bewegung die Motor ausführt (typ. 5)
    icon: mdi:timer-cog

counter:
  blinds_0_living_room_west_clicks:
    name: "Jalousie West - Klickzähler"
    initial: 0
    icon: mdi:counter

# =========================================================
# Template Sensors
# =========================================================

binary_sensor:
  - platform: template
    sensors:
      blinds_0_living_room_west_tilt_available:
        friendly_name: "Jalousie West - Tilt verfügbar"
        icon_template: mdi:check-circle
        value_template: >
          {# TODO: MQTT SENSOREN - Sensor-IDs anpassen (hr_104) #}
          {% set status = states('sensor.mosquitto_broker_mqtt_logo_hr_104_status') | int(0) %}
          {% set pos = states('sensor.mosquitto_broker_mqtt_logo_hr_104_position_raw') | int(0) %}
          {# TODO: KALIBRIERUNG - max_travel_ticks anpassen (552) #}
          {% set pos_pct = (100.0 * pos / 552) | round(0) | int %}
          {{ status == 1 and pos_pct < 80 }}

# =========================================================
# Automation (Blueprint-Verwendung)
# =========================================================

automation:
  - use_blueprint:
      path: t0bybr/blinds.yaml
      input:
        name: "living_room_west"  # TODO: Raum-Slug anpassen (z.B. bedroom_east)
        floor: "0"  # TODO: Stockwerk anpassen (z.B. "1" für erstes OG)

        cover_entity: cover.blinds_0_living_room_west  # TODO: Entsprechend anpassen

        # TODO: MQTT SENSOREN - Button-Entitäten von deiner LOGO-Konfiguration
        up_button_entity_id: binary_sensor.mosquitto_broker_mqtt_logo_coil_9
        down_button_entity_id: binary_sensor.mosquitto_broker_mqtt_logo_coil_8

        # TODO: MQTT SENSOREN - Position und Status von deiner LOGO-Konfiguration
        position_ticks_sensor_entity_id: sensor.mosquitto_broker_mqtt_logo_hr_104_position_raw
        movement_status_sensor_entity_id: sensor.mosquitto_broker_mqtt_logo_hr_104_status

        # Tilt Entity (für Trigger)
        tilt_enabled_entity_id: input_boolean.blinds_0_living_room_west_tilt_enabled

        # TODO: LOGO COILS - Coil-Nummern für Motor (z.B. 8303, 8304)
        coil_up: 8303
        coil_down: 8304

        # TODO: LOGO REGISTER - Register-Nummern (z.B. 535, 534, 20)
        register_target: 535
        register_max_ticks_limit: 534
        register_counter: 20

        # TODO: KALIBRIERUNG - Gesamter Fahrweg in Ticks (messen!)
        max_travel_ticks: 552

        # TODO: TILT-KONFIGURATION - Zielneigung beim Toggle (typ. 75%)
        tilt_target_default: 75
        # TODO: TILT-KONFIGURATION - Max. Position für Tilt (typ. 80%)
        tilt_position_threshold_pct: 80

# =========================================================
# Template Cover (MQTT → LOGO)
# =========================================================

cover:
  - platform: template
    covers:
      blinds_0_living_room_west:
        friendly_name: "Jalousie Wohnzimmer West"
        unique_id: "blinds_0_living_room_west"

        # Prozent-Position aus Ticks
        position_template: >
          {# TODO: Entity-Namen anpassen (blinds_0_living_room_west) #}
          {% set max_travel_ticks = states('input_number.blinds_0_living_room_west_max_travel_ticks') | int(1) %}
          {# TODO: MQTT SENSOREN - Sensor-ID anpassen (hr_104) #}
          {% set current_ticks    = states('sensor.mosquitto_broker_mqtt_logo_hr_104_position_raw') | float(0) %}
          {% if max_travel_ticks > 0 %}
            {{ (current_ticks / max_travel_ticks * 100) | round(0) }}
          {% else %}
            0
          {% endif %}

        # Status aus LOGO (0/1/2/3)
        value_template: >
          {# TODO: MQTT SENSOREN - Sensor-ID anpassen (hr_104) #}
          {% set s = states('sensor.mosquitto_broker_mqtt_logo_hr_104_status') | int(0) %}
          {% if   s == 1 %} open
          {% elif s == 3 %} opening
          {% elif s == 2 %} closing
          {% else        %} closed
          {% endif %}

        # --- Öffnen (auf 100% Ticks) ---
        open_cover:
          sequence:
            # State auf moving_user setzen
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_state)
            - action: input_select.select_option
              target:
                entity_id: input_select.blinds_0_living_room_west_state
              data:
                option: "moving_user"
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_logo_register_target)
            - action: mqtt.publish
              data:
                topic: "logo/register/set/{{ states('input_number.blinds_0_living_room_west_logo_register_target') | int }}"
                payload: "10000"
            - delay: "00:00:0.2"
            - action: mqtt.publish
              data:
                topic: "logo/register/set/{{ states('input_number.blinds_0_living_room_west_logo_register_target') | int }}"
                payload: "{{ states('input_number.blinds_0_living_room_west_max_travel_ticks') | int }}"

        # --- Schließen (auf 0 Ticks) ---
        close_cover:
          sequence:
            # State auf moving_user setzen
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_state)
            - action: input_select.select_option
              target:
                entity_id: input_select.blinds_0_living_room_west_state
              data:
                option: "moving_user"
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_logo_register_target)
            - action: mqtt.publish
              data:
                topic: "logo/register/set/{{ states('input_number.blinds_0_living_room_west_logo_register_target') | int }}"
                payload: "10000"
            - delay: "00:00:0.2"
            - action: mqtt.publish
              data:
                topic: "logo/register/set/{{ states('input_number.blinds_0_living_room_west_logo_register_target') | int }}"
                payload: "0"

        # --- Stop (10000 bestätigen) ---
        stop_cover:
          sequence:
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_logo_register_target)
            - action: mqtt.publish
              data:
                topic: "logo/register/set/{{ states('input_number.blinds_0_living_room_west_logo_register_target') | int }}"
                payload: "10000"

        # --- Setzen einer absoluten Position in % (→ Ticks) ---
        set_cover_position:
          sequence:
            # State auf moving_user setzen
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_state)
            - action: input_select.select_option
              target:
                entity_id: input_select.blinds_0_living_room_west_state
              data:
                option: "moving_user"
            - variables:
                # TODO: Entity-Namen anpassen (blinds_0_living_room_west_max_travel_ticks)
                max_travel_ticks: "{{ states('input_number.blinds_0_living_room_west_max_travel_ticks') | int(1) }}"
                target_ticks: "{{ (position | float(0) / 100 * max_travel_ticks) | int(0) }}"
            # TODO: Entity-Namen anpassen (blinds_0_living_room_west_logo_register_target)
            - action: mqtt.publish
              data:
                topic: "logo/register/set/{{ states('input_number.blinds_0_living_room_west_logo_register_target') | int }}"
                payload: "{{ target_ticks | int }}"
            # Hinweis: '10000'-Bestätigung erfolgt im Blueprint bei 2/3→0/1

        # --- Tilt-Anzeige: zeigt aktuelle Neigung ---
        # TODO: Entity-Namen anpassen (blinds_0_living_room_west_tilt_current)
        tilt_template: "{{ states('input_number.blinds_0_living_room_west_tilt_current') | int(0) }}"
